### ISSUE TITLE
How to read event dat file?

### ISSUE THREAD

**Issue by ChidanandKumarKS** [ziweiWWANG/SHEF#1]
Any snippet code to read event dat file?

**Comment by ziweiWWANG** [comment]
Hi,

You can use the code here to read .dat file:

https://anu365-my.sharepoint.com/:u:/g/personal/u6456661_anu_edu_au/Ed4UiIQLEgxArV_eQUsah0oBS0R8FrdUZuVbyPUvhYOkkw?e=f3S3lh

Cheers,
Ziwei

**Comment by ChidanandKumarKS** [comment]
@ziweiWWANG , thanks for sharing

**Comment by ftyfty123** [comment]
Nice work! I want to read event data in log_td.dat but the above link has expired

**Comment by ftyfty123** [comment]
Nice work! I want to read event data in log_td.dat but the above link is expired. Could you please reopen it again?

**Comment by ziweiWWANG** [comment]
> Nice work! I want to read event data in log_td.dat but the above link is expired. Could you please reopen it again?

Hi there,

You can find the file in: prophesee_tools/load_atis_data.m

Or find the direct link: https://anu365-my.sharepoint.com/:u:/g/personal/u6456661_anu_edu_au/Ed4UiIQLEgxArV_eQUsah0oBS0R8FrdUZuVbyPUvhYOkkw?e=fejeac

**Comment by ftyfty123** [comment]
Thank you for your quick reply. I have already read event data successfully with your method above !
