### ISSUE TITLE
Request for the code of disparity estimation.

### ISSUE THREAD

**Issue by xhchen10** [ziweiWWANG/SHEF#2]
Hi, thank you for the impressive work. I am wondering if there is any plan to publicly release the code of disparity estimation.

**Comment by ziweiWWANG** [comment]
Hi there! Thanks for your interest! I am happy to release the code if that can help you, but I am travelling abroad now. I will be back at uni next month. Thank you :)

**Comment by xhchen10** [comment]
Thank you so much for the quick reply. Enjoy your tour :)

**Comment by xhchen10** [comment]
Hi Ziwei! Could you describe the detailed structure of your DCNet? or Could you share the code fragment of DCNet? Thanks a lot :)

**Comment by ziweiWWANG** [comment]
The network has two parts. The first part is based on the paper "Autodispnet: Improving disparity estimation with automl". We use image + event frame to estimate a new disparity map. Let's call it D_new. Notably, the encoders for the image and event frame are different. You can use a popular downsampling image encoder, but we suggest adding some more conv layers for event frame encoding. The second part is an Unet-based fusion block. The inputs are the D_new and the pre-estimated sparse disparity map D_p in the paper. The fusion block fuses the two images to generate the completion disparity.

Hope it helps!

Cheers,
Ziwei
