### ISSUE TITLE
The data link has expired QAQ

### ISSUE THREAD

**Issue by HYLZ-2019** [ziweiWWANG/SHEF#3]
The data link has expired. ( The link was good yesterday, but I failed to download the dataset because the connection was too slow.... )
![image](https://github.com/ziweiWWANG/SHEF/assets/51911678/66a92d61-e574-4d23-b024-66aafaf534e3)

**Comment by ziweiWWANG** [comment]
Hi Hanyue,

No worries! The link is working now.

Cheers,
Ziwei

**Comment by ziweiWWANG** [comment]
> The data link has expired. ( The link was good yesterday, but I failed to download the dataset because the connection was too slow.... ) ![image](https://user-images.githubusercontent.com/51911678/281620174-66a92d61-e574-4d23-b024-66aafaf534e3.png)

Hi Hanyue,

No worries! The link is working now.

Cheers,
Ziwei

**Comment by HYLZ-2019** [comment]
Sorry for the disturb, can you reset the link? It seems to be down again.
(I can't find where I put my last download QAQ)

**Comment by ziweiWWANG** [comment]
> Sorry for the disturb, can you reset the link? It seems to be down again. (I can't find where I put my last download QAQ)

Hi! No worries. Just reset the link!

Cheers,
Ziwei

**Comment by ghoshsuman** [comment]
Hi @ziweiWWANG , could you please reset the link? It expired again.

**Comment by ziweiWWANG** [comment]
> Hi @ziweiWWANG , could you please reset the link? It expired again.

Just reset the link!

Cheers,
Ziwei
