### ISSUE TITLE
Inquire for Data PreProcessing Method

### ISSUE THREAD

**Issue by ChipsAhoyM** [ziweiWWANG/SHEF#4]
In the repository, I noticed that the code for data preparation was not included. In the paper, the authors describe extracting image edges using a Sobel filter, while for the event edges, you first convert them into the image domain using e2vid. I was wondering if you would be able to provide your data preparation code or share some detailed instructions on how to replicate this process.

**Comment by ziweiWWANG** [comment]
Hi,

In this paper, I integrated events into intensity images using the high-pass filter, not e2vid. You can find the open-source code for the high-pass filter here: https://github.com/cedric-scheerlinck/dvs_image_reconstruction
Of course, you can choose to use e2vid or any other pure event intensity reconstruction method. 
Code for e2vid: https://github.com/uzh-rpg/rpg_e2vid

For applying the Sobel filter, you can either
1. pre-processing: add one line code before saving the intensity image on disk 
2. post-processing: after saving all intensity images on disk, apply the Sobel filter and then save the edge images.  

For Sobel filter, you can use:
1. Matlab, https://www.mathworks.com/help/images/ref/edge.html
2. Python, https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.sobel.html
3. C++ OpenCV, https://docs.opencv.org/3.4/d2/d2c/tutorial_sobel_derivatives.html 

Hope this helps!

Ziwei

**Comment by ChipsAhoyM** [comment]
Thanks for your response!
